// import quiz from "../../../Images/portfolio/portfolio-quiz-app.png"
const data = [{
    id:1,
    cover: "https://www.knowledgehut.com/_next/image?url=https%3A%2F%2Fd2o2utebsixu4k.cloudfront.net%2Fmedia%2Fimages%2F1648454556462-Image-5.png&w=750&q=75",
    title:"Quiz Game",
    category:"Javascript",
    author:"clintNgeno",
    description:"",
},
{
    id:2,
    cover: "https://i.ytimg.com/vi/N3cq0BHDMOY/maxresdefault.jpg",
    title:"Virtual Keyboard Design",
    stack:"HTML, CSS, JavaScript",
    category:"Javascript",
    author:"clintNgeno",
    description:"",
},
{
    id:3,
    cover:"https://miro.medium.com/max/2400/1*naP6y2unXrmK-kRS3VQAKg@2x.png",
    title:"weather app with dark mode",
    stack:"HTML, CSS, JavaScript",
    category:"Javascript",
    author:"clintNgeno",
    description:"",
},
{
    id:4,
    cover:"https://www.knowledgehut.com/_next/image?url=https%3A%2F%2Fd2o2utebsixu4k.cloudfront.net%2Fmedia%2Fimages%2F1648455416177-Image-12.png&w=750&q=75",
    title:"Job Listings with filtering",
    category:"Javascript",
    stack:"HTML, CSS, JavaScript",
    author:"clintNgeno",
    description:"",
},
{
    id:5,
    cover:"https://www.knowledgehut.com/_next/image?url=https%3A%2F%2Fd2o2utebsixu4k.cloudfront.net%2Fmedia%2Fimages%2F1648454886318-Image-8.png&w=750&q=75",
    title:"Music player",
    category:"Javascript",
    stack:"HTML, CSS, JavaScript",
    author:"clintNgeno",
    description:"",
},
{
    id:6,
    cover:"https://mk0abtastybwtpirqi5t.kinstacdn.com/wp-content/uploads/boostrap-landing-page-template-coming-soon.png",
    title:"Dynamic Product Landing Page",
    stack:"HTML, CSS, Bootstrap, jQuery, JavaScript",
    category:"Landing page",
    author:"clintNgeno",
    description:"",
},
// {
//     id:7,
//     cover:"https://res.cloudinary.com/dz209s6jk/image/upload/v1572260150/Challenges/tybadwn9wwcc10hug3sn.jpg",
//     title:"URL Shortening Landing Page",
//     category:"Landing page",
//     stack:"HTML, CSS, JS, API",
//     author:"clintNgeno",
//     description:"",
// },
// {
//     id:8,
//     cover:"https://www.knowledgehut.com/_next/image?url=https%3A%2F%2Fd2o2utebsixu4k.cloudfront.net%2Fmedia%2Fimages%2F1648454807847-Image-7.png&w=750&q=75",
//     title:"Content Management System",
//     category:"CMS",
//     stack:"HTML, CSS, JavaScript, React",
//     author:"clintNgeno",
//     description:"",
// },
// {
//     id:9,
//     cover:"https://www.knowledgehut.com/_next/image?url=https%3A%2F%2Fd2o2utebsixu4k.cloudfront.net%2Fmedia%2Fimages%2F1648459317471-Image-17.png&w=750&q=75",
//     category:"",
//     stack:"RestApi",
//     author:"clintNgeno",
//     description:"",
// },
]

export default data;